FROM rust:1.55.0

# RUN apk update && apk add rust cargo yasm cmake
RUN apt update
RUN apt install -y yasm cmake python3-pip
RUN alias python=python3

WORKDIR /srv/app/

# base for python
COPY ./src/program_generator/requirements.txt /srv/app/src/program_generator/requirements.txt
RUN pip install -r src/program_generator/requirements.txt

# get our files for openethereum
# NOTE: we don't do `RUN git submodule update --init`. You should do this in the host
COPY ./src/instrumentation_measurement/openethereum /srv/app/src/instrumentation_measurement/openethereum
WORKDIR /srv/app/src/instrumentation_measurement/openethereum/evmbin/

RUN cargo build --release

# get the remainder of our files
COPY ./src/ /srv/app/src/

WORKDIR /srv/app/

# check correct host configuration
RUN chmod a+x /srv/app/src/check_clocksource.sh
RUN /srv/app/src/check_clocksource.sh
